#!/bin/bash
CYLINDER_TEST_EXEC=$PWD"/build/cylinder_fitting_test"

#MODEL PARAMETERS (HOUGH)
ANGLE_BINS=30
RADIUS_BINS=10
POSITION_BINS=100
ORIENTATION_ACCUMULATORS_NUM=30
GAUSSIAN_SPHERE_POINTS_NUM=450
ACCUMULATOR_PEAK_THRESHOLD=0.8
MIN_RADIUS=0.25
MAX_RADIUS=0.35

#RANSAC
NORMAL_DISTANCE_WEIGHT=0.5
MAX_ITERATIONS=1000
DISTANCE_THRESHOLD=0.05
DO_REFINE=0
VISUALIZE=0

## declare an array variable
declare -a arr=("outliers" "noise" "occlusion")
## now loop through the above array
for TEST_TYPE in "${arr[@]}"
do
	# Directory where dataset is stored
	DATASET_DIR=$PWD"/dataset/cylinder_"$TEST_TYPE"/"

	# or do whatever with individual element of the array
	$CYLINDER_TEST_EXEC $DATASET_DIR $ANGLE_BINS $RADIUS_BINS $POSITION_BINS $ORIENTATION_ACCUMULATORS_NUM $GAUSSIAN_SPHERE_POINTS_NUM $ACCUMULATOR_PEAK_THRESHOLD $MIN_RADIUS $MAX_RADIUS $NORMAL_DISTANCE_WEIGHT $MAX_ITERATIONS $DISTANCE_THRESHOLD $DO_REFINE $VISUALIZE
done



