#!/bin/bash
CYLINDER_TEST_EXEC="/home/rui/shape-fitting/build/cylinder_fitting_test"

# Directory where dataset is stored
DATASET_DIR="/home/rui/shape-fitting/dataset/"

#MODEL PARAMETERS (HOUGH)
ANGLE_BINS=30
RADIUS_BINS=10
POSITION_BINS=100
ORIENTATION_ACCUMULATORS_NUM=10
GAUSSIAN_SPHERE_POINTS_NUM=450
ACCUMULATOR_PEAK_THRESHOLD=0.8
MIN_RADIUS=0.45
MAX_RADIUS=0.55

#RANSAC
NORMAL_DISTANCE_WEIGHT=0.5
MAX_ITERATIONS=1000
DISTANCE_THRESHOLD=0.05
DO_REFINE=0

$CYLINDER_TEST_EXEC $DATASET_DIR $ANGLE_BINS $RADIUS_BINS $POSITION_BINS $ORIENTATION_ACCUMULATORS_NUM $GAUSSIAN_SPHERE_POINTS_NUM $ACCUMULATOR_PEAK_THRESHOLD $MIN_RADIUS $MAX_RADIUS $NORMAL_DISTANCE_WEIGHT $MAX_ITERATIONS $DISTANCE_THRESHOLD $DO_REFINE


