#!/bin/bash
CYLINDER_TEST_EXEC=$PWD"/build/cylinder_real_data_test"

#MODEL PARAMETERS (HOUGH)
ANGLE_BINS=30
RADIUS_BINS=20
POSITION_BINS=20
ORIENTATION_ACCUMULATORS_NUM=30
GAUSSIAN_SPHERE_POINTS_NUM=450
ACCUMULATOR_PEAK_THRESHOLD=0.8
MIN_RADIUS=0.02
MAX_RADIUS=0.07
MODE=1
SOFT_VOTING=1
VISUALIZE=1

# Directory where dataset is stored
DATASET_DIR=$PWD"/dataset/test/pointclouds_clusters/"


$CYLINDER_TEST_EXEC $DATASET_DIR"cylinder/" $ANGLE_BINS $RADIUS_BINS $POSITION_BINS $ORIENTATION_ACCUMULATORS_NUM $GAUSSIAN_SPHERE_POINTS_NUM $ACCUMULATOR_PEAK_THRESHOLD $MIN_RADIUS $MAX_RADIUS $MODE $SOFT_VOTING $VISUALIZE

$CYLINDER_TEST_EXEC $DATASET_DIR"box/" $ANGLE_BINS $RADIUS_BINS $POSITION_BINS $ORIENTATION_ACCUMULATORS_NUM $GAUSSIAN_SPHERE_POINTS_NUM $ACCUMULATOR_PEAK_THRESHOLD $MIN_RADIUS $MAX_RADIUS $MODE $SOFT_VOTING $VISUALIZE

$CYLINDER_TEST_EXEC $DATASET_DIR"sphere/" $ANGLE_BINS $RADIUS_BINS $POSITION_BINS $ORIENTATION_ACCUMULATORS_NUM $GAUSSIAN_SPHERE_POINTS_NUM $ACCUMULATOR_PEAK_THRESHOLD $MIN_RADIUS $MAX_RADIUS $MODE $SOFT_VOTING $VISUALIZE
