#!/bin/bash
SPHERE_TEST_EXEC="/home/rui/ws/src/shape_detection_fitting/lib/shape-fitting/build/sphere_fitting_test"

# Directory where dataset is stored
DATASET_DIR="/home/rui/ws/src/shape_detection_fitting/lib/shape-fitting/dataset/sphere/"

#MODEL PARAMETERS (HOUGH)
RADIUS_BINS=10
POSITION_BINS=50
ORIENTATION_ACCUMULATORS_NUM=100
GAUSSIAN_SPHERE_POINTS_NUM=450
ACCUMULATOR_PEAK_THRESHOLD=0.8
MIN_RADIUS=0.45
MAX_RADIUS=0.55

#RANSAC
NORMAL_DISTANCE_WEIGHT=0.5
MAX_ITERATIONS=1000
DISTANCE_THRESHOLD=0.05
DO_REFINE=0

$SPHERE_TEST_EXEC $DATASET_DIR $RADIUS_BINS $POSITION_BINS $ORIENTATION_ACCUMULATORS_NUM $GAUSSIAN_SPHERE_POINTS_NUM $ACCUMULATOR_PEAK_THRESHOLD $MIN_RADIUS $MAX_RADIUS $NORMAL_DISTANCE_WEIGHT $MAX_ITERATIONS $DISTANCE_THRESHOLD $DO_REFINE


